spring.application.name=scheduler
spring.datasource.url=jdbc:mysql://localhost:3306/skyview_scheduler
spring.datasource.username=root
spring.datasource.password=josral123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
